dist: trusty
sudo: required
language: cpp
python: 3.6.6
  
addons:
  apt:
      update: true
            
      packages:
        - doxygen
    
  sources:
        - ubuntu-toolchain-r-test


env:
    global:
    - VERBOSE=1
    
install: 
    - sh ci/.travis_install.sh

script: sh ci/.travis_test.sh 

