site_name: Site
nav:
    - Home: index.md
    - About: about.md
    - API:
        - C++: api/c/
theme:
    name: material
    highlightjs: true
    hljs_style: Hybrid 
    hljs_languages:
        - python
        - bash
        - c++
